import { useNavigate } from "react-router-dom";
import Navbar from "../../components/navbar/Navbar";
import "./HowItWorksPage.css";

const steps = [
  {
    number: "01",
    title: "Upload Resume & Profile",
    description: "Drag and drop your PDF resume. Our parsing engine analyzes your core skills, experience level, and past projects to personalize the upcoming session.",
    colorClass: "blue"
  },
  {
    number: "02",
    title: "Define Target Role",
    description: "Specify the exact job title and years of experience you are practicing for. The simulator adapts the context and difficulty of technical questions accordingly.",
    colorClass: "purple"
  },
  {
    number: "03",
    title: "Dynamic AI Interviewing",
    description: "Answer real-world technical scenario questions dynamically generated by Gemini. Work through the session questions at your own pace.",
    colorClass: "indigo"
  },
  {
    number: "04",
    title: "Comprehensive Report Card",
    description: "Unlock an instant, multi-dimensional feedback dashboard. Analyze your overall performance, strengths, growth areas, question-by-question scores, and ideal answers.",
    colorClass: "green"
  }
];

function HowItWorksPage() {
  const navigate = useNavigate();

  return (
    <div className="container">
      <Navbar />

      <div className="how-it-works-layout animate-fade-in">

        <div className="ambient-orb orb-top-left"></div>
        <div className="ambient-orb orb-bottom-right"></div>

        <header className="how-header-block">
          <h1 className="how-title">How the Simulator Works</h1>
          <p className="how-subtitle">
            An automated, AI-driven process designed to mirror real technical assessment pipelines.
          </p>
        </header>

        <div className="steps-grid">
          {steps.map((step) => (
            <div key={step.number} className={`step-card-card ${step.colorClass}`}>
              <div className="step-card-header">
                <span className="step-card-number">{step.number}</span>
              </div>
              <h2 className="step-card-title">{step.title}</h2>
              <p className="step-card-description">{step.description}</p>
            </div>
          ))}
        </div>

        <div className="how-action-footer">
          <button 
            className="how-cta-btn" 
            type="button" 
            onClick={() => navigate("/")}
          >
            <span className="btn-content-wrapper">
              Try It Now
              <svg className="btn-arrow-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12" />
                <polyline points="12 5 19 12 12 19" />
              </svg>
            </span>
          </button>
        </div>
      </div>
    </div>
  );
}

export default HowItWorksPage;
